site:
  title: Diego Patterson Personal Portfolio
  description: This is a collection of my code and projects that I can share as well as a way to contact me.
  url: https://www.diegopattersonCode.com
  baseurl: /   # Change if your site is hosted in a subdirectory
