version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - echo Installing Bundler...
      - gem install bundler
      - echo Installing dependencies...
      - bundle install
  pre_build:
    commands:
      - echo Preparing to build the Jekyll site...
  build:
    commands:
      - echo Building the Jekyll site...
      - bundle exec jekyll build
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync _site/ s3://your-s3-bucket-name --delete
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: _site
  discard-paths: yes

cache:
  paths:
    - vendor/bundle/**/*